### ISSUE TITLE
0.0.6

### ISSUE THREAD

**Issue by woodnaonly** [LeiSangSang/ff14risingstone_task#3]
0.0.6打开就卡住了 没有二维码
0.0.5 可以有二维码 有时候扫完吗会闪退
用的exe

**Comment by LeiSangSang** [comment]
0.0.6请检查跟api.github.com的连通情况.
0.0.7版本去除了版本检查,可以试试

**Comment by woodnaonly** [comment]
确实好了，我挂着v2ray，应该是默认没走系统代理。
