### ISSUE TITLE
发评论五条提示，操作太快，请稍后再试

### ISSUE THREAD

**Issue by woodnaonly** [LeiSangSang/ff14risingstone_task#4]
版本0.0.7

可否提个建议，加个循环每24小时重复一次，cookie的有效期是够的。

**Comment by woodnaonly** [comment]
----发评论五条----
评论成功
操作太快，请稍后再试
操作太快，请稍后再试
操作太快，请稍后再试
操作太快，请稍后再试
----获取经验结束,按任意键退出----

**Comment by LeiSangSang** [comment]
已修改
https://github.com/LeiSangSang/ff14risingstone_task/releases

**Comment by LeiSangSang** [comment]
循环功能有空再加吧,因为有些cookie是会话的,有些是要去登录里刷的,暂时没工夫分析
